import type { Metadata } from "next";
import "../ui/globals.css";
import { HelveticaLTStd } from "@/ui/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={HelveticaLTStd.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
