import type { Metadata } from "next";
import "../ui/globals.css";
import { HelveticaLTStd } from "@/ui/fonts/fonts";
import Footer from "@/ui/components/footer";
import Header from "@/ui/components/client-header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={HelveticaLTStd.className}>
            <body className="bg-tavo-light flex h-dvh flex-col px-195">
                {/* <Header /> */}
                {children}
                {/* <Footer /> */}
            </body>
        </html>
    );
}
