services:
  - type: web
    name: laravel-backend
    env: docker
    plan: starter
    autoDeploy: true
    buildContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    # Commandes post-déploiement en prod
    postDeployCommand: |
      php artisan config:clear
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_URL
        value: https://stage-rtbf-entreprise.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: APP_KEY
        sync: false