services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    autoDeploy: true
    buildContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    # Commandes post-déploiement en prod
    postDeployCommand: |
      mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views
      mkdir -p bootstrap/cache
      chown -R www-data:www-data storage bootstrap/cache
      chmod -R 775 storage bootstrap/cache
      php artisan config:clear
      php artisan migrate --force
      php artisan storage:link || true
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    disk:
      name: storage
      mountPath: /var/www/html/storage
      sizeGB: 5
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_URL
        value: https://stage-rtbf-entreprise.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: APP_KEY
        sync: false